# Generated by Django 5.1.6 on 2025-02-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.IntegerField(choices=[(1, 'Нравится')], verbose_name='Значение'),
        ),
    ]
