# Generated by Django 5.1.6 on 2025-02-22 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_rating_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rating',
            name='news_rating_time_cr_6857f8_idx',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('post', 'user', 'ip_address')},
        ),
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['-time_create'], name='news_rating_time_cr_6b8024_idx'),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='value',
        ),
    ]
