# Generated by Django 5.1.6 on 2025-02-22 21:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_rating_news_rating_time_cr_6857f8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes_count',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('post', 'user')},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='ip_address',
        ),
    ]
