# Generated by Django 5.1.6 on 2025-02-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_post_likes_count_alter_rating_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='value',
            field=models.BooleanField(default=False, verbose_name='Лайк'),
        ),
    ]
