# Generated by Django 5.1.6 on 2025-02-22 21:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rating_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rating',
            name='news_rating_time_cr_6b8024_idx',
        ),
        migrations.AddField(
            model_name='rating',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, verbose_name='IP Адрес'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['-time_create', 'value'], name='news_rating_time_cr_6857f8_idx'),
        ),
    ]
