# Generated by Django 5.1.6 on 2025-02-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_rating_news_rating_time_cr_6b8024_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rating',
            name='news_rating_time_cr_6857f8_idx',
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.IntegerField(choices=[(1, 'Нравится')], verbose_name='Значение'),
        ),
    ]
